//
//  AKDBManager+UserGroup.m
//  Project
//
//  Created by ankye on 2016/12/13.
//  Copyright © 2016年 ankye. All rights reserved.
//

#import "AKDBManager+UserGroup.h"

@implementation AKDBManager (UserGroup)


AKDB_CREATE_TABLE_IMPL(user_group,KAK_TLUSER_DBNAME,TABLE_NAME_GROUP,SQL_CREATE_TABLE_GROUP)

AKDB_INSERT_OR_UPDATE_IMPL(user_group,AKUserGroup,KAK_TLUSER_DBNAME,TABLE_NAME_GROUP,SQL_INSERT_OR_UPDATE_GROUP)

AKDB_UPDATE_BY_ID_AND_ANOTHER_ID_IMPL(user_group,@"uid",@"gid",KAK_TLUSER_DBNAME,TABLE_NAME_GROUP)

AKDB_QUERY_ROWS_BY_ID_IMPL(user_group,AKUserGroup,KAK_TLUSER_DBNAME,SQL_SELECT_USER_GROUPS,SQL_SELECT_USER_ROWS)

AKDB_QUERY_ROW_BY_ID_IMPL(user_group,AKUserGroup,KAK_TLUSER_DBNAME,TABLE_NAME_GROUP,SQL_SELECT_USER_GROUP)

AKDB_DELETE_BY_ID_AND_ANOTHER_ID_IMPL(user_group,KAK_TLUSER_DBNAME,TABLE_NAME_GROUP,SQL_DELETE_GROUP)



@end
